YUI.add("yuidoc-meta", function(Y) {
   Y.YUIDoc = { meta: {
    "classes": [
        "AdminNavigation",
        "AdminSubnavService",
        "AnalyticsManager",
        "ApiActionController",
        "ArticleRenderer",
        "ArticleService",
        "ArticleServiceV2",
        "AsyncEventEmitter",
        "AsyncJobRunner",
        "AudioMediaRenderer",
        "BaseAdminController",
        "BaseApiController",
        "BaseBodyParser",
        "BaseController",
        "BaseMediaRenderer",
        "BaseObjectService",
        "CacheEntityService",
        "CacheFactory",
        "CacheLockProvider",
        "CallHomeService",
        "ClientJs",
        "ClusterJobRunner",
        "CommandService",
        "CommentService",
        "ContentObjectService",
        "ContentService",
        "ContentViewLoader",
        "CustomObjectService",
        "DAO",
        "DBManager",
        "DBMigrate",
        "DailyMotionMediaRenderer",
        "DbEntityService",
        "DbLockProvider",
        "DeleteController",
        "DocumentCreator",
        "EmailService",
        "ErrorFormatters",
        "ErrorViewController",
        "ErrorsOverTime",
        "FSEntityService",
        "FormAuthentication",
        "FormBodyParser",
        "FormController",
        "FsMediaProvider",
        "ImageMediaRenderer",
        "InstagramMediaRenderer",
        "JSONFSEntityService",
        "JobRunner",
        "JobService",
        "JsonBodyParser",
        "KickStarterMediaRenderer",
        "LibrariesService",
        "Localization",
        "LockService",
        "MediaLoader",
        "MediaService",
        "MediaServiceV2",
        "MemoryEntityService",
        "MongoCommandBroker",
        "MongoMediaProvider",
        "MongoRegistrationProvider",
        "MongoSessionStore",
        "PB",
        "PBError",
        "PageRenderer",
        "PageService",
        "PasswordResetService",
        "PdfMediaRenderer",
        "PencilBlue",
        "PluginRepository",
        "PluginService",
        "PluginSettingService",
        "ReadOnlySimpleLayeredService",
        "RedisCommandBroker",
        "RedisRegistrationProvider",
        "RedisSessionStore",
        "RequestHandler",
        "SectionService",
        "SecurityService",
        "ServerInitializer",
        "ServerRegistration",
        "SessionHandler",
        "SettingService",
        "SettingsServiceFactory",
        "SimpleLayeredService",
        "SiteActivateJob",
        "SiteCreateEditJob",
        "SiteDeactivateJob",
        "SiteJobRunner",
        "SiteMapService",
        "SiteQueryService",
        "SiteService",
        "SlideShareMediaRenderer",
        "StorifyMediaRenderer",
        "System",
        "TTLIndexHelper",
        "TemplateEntityService",
        "TemplateService",
        "TemplateValue",
        "TokenAuthentication",
        "TokenService",
        "TopMenuService",
        "TopicService",
        "TrinketMediaRenderer",
        "UrlService",
        "UserService",
        "UsernamePasswordAuthentication",
        "Util",
        "ValidationService",
        "VideoMediaRenderer",
        "View Controller",
        "VimeoMediaRenderer",
        "VineMediaRenderer",
        "YouTubeMediaRenderer"
    ],
    "modules": [
        "Admin",
        "Database",
        "Entities",
        "ErrorSuccess",
        "Model",
        "Security",
        "Services",
        "Session",
        "Storage",
        "Theme",
        "dao"
    ],
    "allModules": [
        {
            "displayName": "Admin",
            "name": "Admin",
            "description": "Provides function to construct the structure needed to display the navigation\nin the Admin section of the application."
        },
        {
            "displayName": "dao",
            "name": "dao",
            "description": "Creates the cache"
        },
        {
            "displayName": "Database",
            "name": "Database",
            "description": "Controlls the data model"
        },
        {
            "displayName": "Entities",
            "name": "Entities",
            "description": "Service for performing user specific operations."
        },
        {
            "displayName": "ErrorSuccess",
            "name": "ErrorSuccess",
            "description": "Specialized application error that knows what status code to return"
        },
        {
            "displayName": "Model",
            "name": "Model",
            "description": "Creates structures for persistence and cleans various fields."
        },
        {
            "displayName": "Security",
            "name": "Security",
            "description": "Service for managing user access"
        },
        {
            "displayName": "Services",
            "name": "Services",
            "description": "Service for creating JavaScript tags"
        },
        {
            "displayName": "Session",
            "name": "Session",
            "description": "Session storage backed by MongoDB"
        },
        {
            "displayName": "Storage",
            "name": "Storage",
            "description": "Services for managing storage"
        },
        {
            "displayName": "Theme",
            "name": "Theme",
            "description": "Theme content services"
        }
    ],
    "elements": []
} };
});